### ISSUE TITLE
import时报错

### ISSUE THREAD

**Issue by bigpigeon** [shanelau/zhihu#11]
>var zhihu = require("zhihu")
Unhandled rejection TypeError: Cannot read property 'parent' of undefined
    at exports.update (/node_modules/cheerio/lib/parse.js:62:25)
    at module.exports (/node_modules/cheerio/lib/parse.js:24:3)
    at Function.exports.load (/node_modules/cheerio/lib/static.js:19:14)
    at getItems (/node_modules/zhihu/api/Collection.js:18:19)
    at /node_modules/zhihu/api/Collection.js:67:12
    at bound (domain.js:287:14)
    at runBound (domain.js:300:12)
    at tryCatcher (/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/node_modules/bluebird/js/release/promise.js:503:31)
    at Promise._settlePromise (/node_modules/bluebird/js/release/promise.js:560:18)
    at Promise._settlePromise0 (/node_modules/bluebird/js/release/promise.js:605:10)
    at Promise._settlePromises (/node_modules/bluebird/js/release/promise.js:684:18)
    at Promise._fulfill (/node_modules/bluebird/js/release/promise.js:629:18)
    at Request._callback (/node_modules/bluebird/js/release/nodeback.js:42:21)
    at Request.self.callback (/node_modules/request/request.js:200:22)
    at emitTwo (events.js:100:13)

**Comment by shanelau** [comment]
知乎改了 https ,很多功能受到影响。本版本不会 报错了。  请升级到 1.0.0
